[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_GOOGLE_CLIENT_ID = "your_google_client_id_here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000